import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { majors, courses, students, advisingPeriods } from '@/lib/db/schema';

export async function POST(request: NextRequest) {
  try {
    const pbhlMajor = await db.insert(majors).values({
      code: 'PBHL',
      name: 'Public Health',
      description: 'Bachelor of Science in Public Health',
      isActive: true,
    }).returning();
    
    const majorId = pbhlMajor[0].id;
    
    await db.insert(courses).values([
      {
        majorId,
        code: 'PBHL 101',
        name: 'Introduction to Public Health',
        credits: 3,
        type: 'required',
        semester: 1,
        offered: true,
        prerequisites: [],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 201',
        name: 'Health Behavior',
        credits: 3,
        type: 'required',
        semester: 2,
        offered: true,
        prerequisites: ['PBHL 101'],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 202',
        name: 'Health Policy Foundations',
        credits: 3,
        type: 'required',
        semester: 2,
        offered: true,
        prerequisites: ['PBHL 101'],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 301',
        name: 'Epidemiology',
        credits: 3,
        type: 'required',
        semester: 3,
        offered: true,
        prerequisites: ['PBHL 201'],
        corequisites: [],
        concurrent: ['PBHL 305'],
      },
      {
        majorId,
        code: 'PBHL 305',
        name: 'Biostatistics',
        credits: 3,
        type: 'required',
        semester: 3,
        offered: true,
        prerequisites: ['MATH 101'],
        corequisites: [],
        concurrent: ['PBHL 301'],
      },
      {
        majorId,
        code: 'PBHL 310',
        name: 'Environmental Health',
        credits: 3,
        type: 'required',
        semester: 4,
        offered: true,
        prerequisites: ['PBHL 301'],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 320',
        name: 'Health Policy',
        credits: 3,
        type: 'required',
        semester: 4,
        offered: true,
        prerequisites: ['PBHL 202'],
        corequisites: [],
        concurrent: [],
        standingRequired: 'Junior standing',
      },
      {
        majorId,
        code: 'PBHL 350',
        name: 'Global Health',
        credits: 3,
        type: 'intensive',
        semester: 5,
        offered: true,
        prerequisites: ['PBHL 201'],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 355',
        name: 'Community Health',
        credits: 3,
        type: 'intensive',
        semester: 5,
        offered: true,
        prerequisites: ['PBHL 201'],
        corequisites: [],
        concurrent: [],
      },
      {
        majorId,
        code: 'PBHL 401',
        name: 'Capstone I',
        credits: 3,
        type: 'required',
        semester: 7,
        offered: true,
        prerequisites: ['PBHL 301', 'PBHL 305', 'PBHL 310'],
        corequisites: [],
        concurrent: [],
        standingRequired: 'Senior standing',
      },
      {
        majorId,
        code: 'PBHL 402',
        name: 'Capstone II',
        credits: 3,
        type: 'required',
        semester: 8,
        offered: true,
        prerequisites: ['PBHL 401'],
        corequisites: [],
        concurrent: [],
        standingRequired: 'Senior standing',
      },
      {
        majorId,
        code: 'MATH 101',
        name: 'College Algebra',
        credits: 3,
        type: 'required',
        semester: 1,
        offered: true,
        prerequisites: [],
        corequisites: [],
        concurrent: [],
      },
    ]);
    
    await db.insert(students).values([
      {
        majorId,
        studentId: '202401001',
        name: 'John Smith',
        email: 'john.smith@university.edu',
        standing: 'Junior',
        creditsCompleted: 45,
        creditsRegistered: 12,
        creditsRemaining: 63,
        courseStatuses: {
          'PBHL 101': 'c',
          'PBHL 201': 'c',
          'PBHL 202': 'c',
          'MATH 101': 'c',
          'PBHL 301': 'r',
          'PBHL 305': 'r',
        },
      },
      {
        majorId,
        studentId: '202401002',
        name: 'Sarah Johnson',
        email: 'sarah.johnson@university.edu',
        standing: 'Sophomore',
        creditsCompleted: 30,
        creditsRegistered: 15,
        creditsRemaining: 75,
        courseStatuses: {
          'PBHL 101': 'c',
          'MATH 101': 'c',
          'PBHL 201': 'r',
          'PBHL 202': 'r',
        },
      },
      {
        majorId,
        studentId: '202401003',
        name: 'Mike Williams',
        email: 'mike.williams@university.edu',
        standing: 'Senior',
        creditsCompleted: 90,
        creditsRegistered: 12,
        creditsRemaining: 18,
        courseStatuses: {
          'PBHL 101': 'c',
          'PBHL 201': 'c',
          'PBHL 202': 'c',
          'MATH 101': 'c',
          'PBHL 301': 'c',
          'PBHL 305': 'c',
          'PBHL 310': 'c',
          'PBHL 320': 'c',
          'PBHL 350': 'c',
          'PBHL 355': 'c',
          'PBHL 401': 'r',
        },
      },
      {
        majorId,
        studentId: '202401004',
        name: 'Emily Brown',
        email: 'emily.brown@university.edu',
        standing: 'Freshman',
        creditsCompleted: 12,
        creditsRegistered: 12,
        creditsRemaining: 96,
        courseStatuses: {
          'PBHL 101': 'r',
          'MATH 101': 'r',
        },
      },
      {
        majorId,
        studentId: '202401005',
        name: 'David Lee',
        email: 'david.lee@university.edu',
        standing: 'Junior',
        creditsCompleted: 60,
        creditsRegistered: 9,
        creditsRemaining: 51,
        courseStatuses: {
          'PBHL 101': 'c',
          'PBHL 201': 'c',
          'PBHL 202': 'c',
          'MATH 101': 'c',
          'PBHL 301': 'c',
          'PBHL 305': 'f',
          'PBHL 350': 'r',
        },
      },
    ]);
    
    await db.insert(advisingPeriods).values({
      majorId,
      semester: 'Spring',
      year: 2025,
      advisorName: 'Dr. Jane Wilson',
      isActive: true,
    });
    
    return NextResponse.json({ 
      message: 'Seed data created successfully',
      majorId,
    });
  } catch (error) {
    console.error('Error seeding data:', error);
    return NextResponse.json({ error: 'Failed to seed data', details: String(error) }, { status: 500 });
  }
}
